[package]
name = "api-exec"
version = "0.1.0"
authors = ["clp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.11.1"
async-trait = "0.1.50"
chrono = "0.4.19"
crossbeam-queue = "0.3.1"
