name: CI
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
      - run: |
          for manifest in 'find crates -name Cargo.toml'
          do
            echo check fmt for $manifest
            cargo fmt --all --manifest-path $manifest -- --check
          done

  test:
    runs-on: ${{ matrix.os }}
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_TEST_DEBUG: 1
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            other: i686-unknown-linux-gnu
          - os: macos-latest
            rust: stable
            other: x86_64-apple-ios
          - os: windows-latest
            rust: stable-msvc
            other: i686-pc-windows-msvc

